# Generated by Django 5.1.2 on 2024-10-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputFromsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('roll_number', models.IntegerField(help_text='Enter 6 digit roll number')),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
